# Generated by Django 5.1.4 on 2025-01-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertweet', '0002_alter_usertweets_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertweets',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
